




const a=Promise.reject(
  'a'
).then(
  val => val
).catch(
  err => Promise.reject(err)
);


a.then(console.log)
  .catch(console.error);
     

